version: "3.9"

services:
  juice:
    image: bkimminich/juice-shop:14.9.1
    restart: unless-stopped
    networks:
      siem_macvlan:
        ipv4_address: 172.16.45.150
    environment:
      - NODE_ENV=production
    # Ship container logs to your SIEM (optional but handy)
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "udp://${SIEM_IP}:${SIEM_PORT}"
    #     tag: "juice-shop"

networks:
  siem_macvlan:
    driver: macvlan
    driver_opts:
      parent: ens33
    ipam:
      config:
        - subnet: 172.16.45.0/24
          gateway: 172.16.45.1

