- name: Configure syslog-ng to listen on TCP/514 and write to a file
  copy:
    dest: /etc/syslog-ng/conf.d/10-recv-apache.conf
    mode: "0644"
    content: |
      # Listen on all interfaces for web VM logs
      source s_net { tcp(ip("0.0.0.0") port({{ syslog_port }})); };

      # For quick validation; swap this for Elasticsearch/Logstash later
      destination d_apache { file("/var/log/siem/apache.log"); };

      log { source(s_net); destination(d_apache); };
  notify: Restart syslog-ng
