---
- name: Check if syslog-ng repo list exists
  ansible.builtin.stat:
    path: "{{ syslogng_list }}"
  register: syslogng_list_stat

- name: Install syslog-ng repo (idempotent)
  when: not syslogng_list_stat.stat.exists
  become: true
  block:
    - name: Download syslog-ng repo key (ASCII)
      ansible.builtin.get_url:
        url: https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc
        dest: /tmp/syslog-ng-ose.asc
        mode: '0644'

    - name: Convert syslog-ng key to dearmored keyring
      ansible.builtin.command:
        cmd: "gpg --dearmor -o {{ syslogng_keyring }} /tmp/syslog-ng-ose.asc"
      args:
        creates: "{{ syslogng_keyring }}"

    - name: Add syslog-ng APT repo
      ansible.builtin.copy:
        dest: "{{ syslogng_list }}"
        content: |
          deb [signed-by={{ syslogng_keyring }}] https://ose-repo.syslog-ng.com/apt/ stable ubuntu-jammy
        owner: root
        group: root
        mode: '0644'

    - name: Update package
      ansible.builtin.package:
        update_cache: yes

- name: Install build and runtime packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_dependencies }}"

- name: Ensure docker engine is installed
  block:
    - name: Check if docker command exists
      command: which docker
      register: docker_exists
      changed_when: false
      failed_when: false

    - name: Install Docker using get.docker.com
      shell: curl -fsSL https://get.docker.com/ | sh
      when: docker_exists.rc != 0

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true


