---
- name: Configure SIEM
  hosts: siems
  become: true
  roles:
    - siem

- name: Configure Target
  hosts: targets
  become: true
  roles:
    - target

- name: Configure Attacker
  hosts: attackers
  become: true
  roles:
    - attacker
