#SPDX-License-Identifier: MIT-0
---
# handlers file for target
- name: Reload Apache
  service:
    name: apache2
    state: reloaded
  listen: Reload Apache

- name: Restart syslog-ng
  service:
    name: syslog-ng
    state: restarted
    enabled: true
  listen: Restart syslog-ng
