---
- name: Clone Juice Shop
  ansible.builtin.git:
    repo: https://github.com/juice-shop/juice-shop.git
    dest: "{{ app_dir }}"
    version: master
    depth: 1
    update: yes
  register: juice_git

- name: Check if node_modules exists
  ansible.builtin.stat:
    path: "{{ app_dir }}/node_modules"
  register: node_modules_stat

- name: Install npm dependencies
  ansible.builtin.command: "{{ node_bin_dir }}/npm install --omit=dev"
  args:
    chdir: "{{ app_dir }}"
  environment:
    PATH: "{{ node_path }}"
  when: juice_git.changed or not node_modules_stat.stat.exists
  register: npm_install
  changed_when: "'added' in npm_install.stdout or 'removed' in npm_install.stdout or 'audited' in npm_install.stdout"

- name: Create systemd unit for Juice Shop
  ansible.builtin.copy:
    dest: /etc/systemd/system/juice-shop.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=OWASP Juice Shop
      After=network-online.target
      Wants=network-online.target

      [Service]
      WorkingDirectory={{ app_dir }}
      Environment=NODE_ENV=production
      Environment=PATH={{ node_path }}
      ExecStart={{ node_bin_dir }}/npm start -- --host=0.0.0.0 --port=8080
      Restart=always
      RestartSec=3
      User=root
      Group=root
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target

- name: Enable and start juice-shop
  ansible.builtin.systemd:
    name: juice-shop
    state: restarted
    enabled: yes
    daemon_reload: yes

