#SPDX-License-Identifier: MIT-0
---
- name: Run ldconfig
  command: ldconfig

- name: Restart syslog-ng
  service:
    name: syslog-ng
    state: restarted
    enabled: true
  listen: Restart syslog-ng
